-- CreateTable
CREATE TABLE "Candidate" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "photoUrl" TEXT NOT NULL,
    "like" INTEGER NOT NULL DEFAULT 0,
    "love" INTEGER NOT NULL DEFAULT 0,
    "care" INTEGER NOT NULL DEFAULT 0,
    "haha" INTEGER NOT NULL DEFAULT 0,
    "wow" INTEGER NOT NULL DEFAULT 0,
    "sad" INTEGER NOT NULL DEFAULT 0,
    "angry" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
